### ISSUE TITLE
Two more suggestions

### ISSUE THREAD

**Issue by prko** [shimpe/panola#2]
Hello!

Thank you for this amazing quarks extension.
I know several ways to notate score using codes, and Panola is the most efficient and attractive.
It is very comprehensive and musician-friendly.

1. What I firstly would like to suggest is just for less typing because I am lazy.
Could you implement another one symbol which can be used as \\ so that users can do the same thing by pressing a key one time instead of by pressing \ twice?
If you allocate @, we can write
```supercollider
(
~ex = Panola.new("c4@tempo{80}@vol{0.2} d e f g@vol{0.9} a b c5@tempo{160}@vol{0.2}");
~player = ~ex.asPbind.play;
)
```

2. What I firstly would like to suggest now is supporting float MIDI note pitches. It has two advantages:
  1. it is better for applying algorisms
  2. it enables microtonality
```supercollider
(
~ex = Panola.new("60 60.0625 60.125 60.25");
~player = ~ex.asPbind.play;
)
```

I already suggested independency of individual pitches of chords such as duration, \\vol and \\pdur.

I think Panola will be the best notation system which is even better than traditional notation using 5-line staves if it provides these things!

Thank you for reading and thank you for providing Panola!!

**Comment by shimpe** [comment]
Hi @prko,

Thanks for trying Panola and taking your time to provide some feedback.

Using the @ sign for sure is possible, I can look into it. 

Microtonality is a bit more problematic because Panola is also used to generate MIDI (I mostly use it to drive a hardware synthesizer) and MIDI has no good support for microtonality. 

Well... the story is more nuanced. MIDI in fact has extremely good support for microtonality, but it does so by changing the mapping from integer midi note number to frequency, i.e. the midi note numbers remain integers, but map to frequencies in a different way. On a hardware synthesizer this typically means uploading some midi note to frequency lookup table by means of either the midi tuning standard or some non-standardized system like a .tun file. 

If one does not want to use the midi standard, but still wants to have some microtonality, there's a cludge where the fractional part of the midi note number is translated to a pitch bend message (I once posted some code on the mailing list for this), but the drawbacks of this system are two-fold: 1. synths do not have a standardized pitch bend range so you need to configure the pitch bend range for your synth as a parameter in the code, 2. pitch bend affects all notes on a given midi channel simultaneously, so it will typically not lead to the results you want anyway.

Of course I could adopt a convention where MIDI streams only output the integer part of a fractional midi note number, whereas supercollider pbinds use the complete number. On one hand I don't like how it leads to an inconsistency between "internal" (pbind) and "external" (midi) usage, but on the other hand it's well defined what will happen if only you know what your are doing.

So I can imagine adding microtonality using fractional midi numbers for supercollider internal use only, but I'm not sure how easy it will be to adapt the parsing. Sclang is not my favorite language when it comes to text parsing. I'll consider it.

**Comment by shimpe** [comment]
@prko : the @ sign has been added, the microtonality is still under consideration.

**Comment by prko** [comment]
Thank you very much for adding @ and considering microtonality.

**Comment by shimpe** [comment]
Microtonality is now available using the sister project https://github.com/shimpe/mitola
